version: '3.1'

services:

  db:
    image: 'mongo'
    restart: always
    container_name: MONGODB_LOJA
    environment:
     - MONGO_INITDB_ROOT_USERNAME=user123
     - MONGO_INITDB_ROOT_PASSWORD=product123
    ports:
      - '27018:27017'

  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
        - MONGO_HOST=host.docker.internal
        - MONGO_URI=LojaDB?authSource=admin
        - MONGO_USER=user123
        - MONGO_PASS=product123
        - SERVER_PORT=8081
        - NODE_ENV=development
    volumes:
        - ./:/home/node/app
    ports:
        - 8081:8081
    command: "npm run dev"
    depends_on:
        - db