# Use postgres/example user/password credentials
version: '3.1'

services:

  db1:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: compras
    ports:
      - 25435:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8051:8080

  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
        - DATABASE_PORT=25435
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=example
        - DATABASE=compras
        - DATABASE_HOST=host.docker.internal
        - NODE_ENV=development
        - SERVER_PORT=8082
    volumes:
        - ./:/home/node/app
    ports:
        - 8082:8082
    command: "npm run dev"
    depends_on:
        - db1